### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by Yow888** [BobHasNoSoul/jellyfin-avatars#1]
Hello, the user-profile-index-html.*.bundle.js file no longer contains <span>${DeleteImage}</span> </button> 

Celui-ci ne contient que  
`"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[7366],{21524:function(e,a,r){r.r(a),a.default='<div id="userProfilePage" data-role="page" class="page libraryPage userPreferencesPage userPasswordPage noSecondaryNavPage" data-title="${Profile}" data-menubutton="false"> </div> '}}]);`

**Comment by samucamg** [comment]
in the new version, do not have this file anymore user-profile-index-html.*.bundle.js

**Comment by BLACK4585** [comment]
Same issue here, an update would be nice.

**Comment by BobHasNoSoul** [comment]
Fixed updated, please test and report back. the ps2 library is currently having issues uploading all the avatars.. so that is a known bug for now git on my cli isnt working properly and keeps timing out part way through upload

**Comment by BLACK4585** [comment]
Yep it's working now. 
Thank you very much!
