### ISSUE TITLE
Image Errors

### ISSUE THREAD

**Issue by BugZappa** [BobHasNoSoul/jellyfin-avatars#7]
After setting up the mod to work along side the Docker-Compose file i've noticed a vast majority of images simply do not load.

![image](https://github.com/user-attachments/assets/4e456cb0-98ee-44a0-b7d3-932606851b6c)
![image](https://github.com/user-attachments/assets/b1187004-1d1a-4ded-9ae7-ce40c2a8de4d)
![image](https://github.com/user-attachments/assets/bf4d720a-4c52-4aa6-bfb5-6a2b5218b1a8)

It doesn't seem to be a permissions I've made sure of it.

![image](https://github.com/user-attachments/assets/db1edfbc-4faf-4f91-b151-fb82e86446e5)

Any ideas are much appreciated!

### [EDIT] After a bit of looking around it appears this only effects the "Steam" and the "PSone" tabs. The "Amazon" tab appears to have a formatting issue where some areas are being skipped over (image below)

![image](https://github.com/user-attachments/assets/a88218e1-497e-4f70-b57a-b5f4cbe4168a)

### [Edit 2] It seems that the filenames are incorrect.

![image](https://github.com/user-attachments/assets/d29251f8-93ed-4e17-abb5-f0e1923e7adc)
![image](https://github.com/user-attachments/assets/d976fb40-421a-4df5-95a1-4aea305125a7)
![image](https://github.com/user-attachments/assets/03505ce9-03ae-4c9f-b34d-fd548084221e)
![image](https://github.com/user-attachments/assets/a9a5a9e8-a296-41cb-9685-1a6b02a9a580)

I guess for the time being ill manually update these files.

**Comment by BobHasNoSoul** [comment]
Okay so this is either a permission error or a volume error (there are two
sets of issues this could be)

However I would try this first to be 100% sure it's not permission related

On your system not in docker run

sudo docker chmod -R 777 /path/to/avatars

The second would be the volume having an error in mounting

Can you explain exactly how you mounted the volume inside docker? Because
it is very.. what's the word.. specific on docker

**Comment by BugZappa** [comment]
> Okay so this is either a permission error or a volume error (there are two sets of issues this could be) However I would try this first to be 100% sure it's not permission related On your system not in docker run sudo docker chmod -R 777 /path/to/avatars The second would be the volume having an error in mounting Can you explain exactly how you mounted the volume inside docker? Because it is very.. what's the word.. specific on docker

Hey Bob, it appears you haven't seen my edit to this issue. The files throwing errors don't exist on my file-system, i suppose at some point they were updated along side their filenames which is causing this issue for me.

**Comment by BobHasNoSoul** [comment]
Ahh I didn't see the update (currently at work so using mail client to
respond I will have a deeper look when I get home)

**Comment by BugZappa** [comment]
> Ahh I didn't see the update (currently at work so using mail client to
> 
> respond I will have a deeper look when I get home)
> 


No worries, I greatly appreciate you looking into it! If you need any troubleshooting done on my end I'll gladly assist.

**Comment by BobHasNoSoul** [comment]
weird it looks like they were removed from the git i will get an update pushed tonight with them again

**Comment by BugZappa** [comment]
Hey @BobHasNoSoul it seems like that did the trick! 

Went an took a look at the Steam images in Jellyfin and it's been consistently crashing my desktop because of how many there are ahaha 😆

**Comment by BugZappa** [comment]
@BobHasNoSoul would like to mention that the weird formatting issue with the Amazon tab is still preset.

I'm not too stressed about this but thought I would mention it.

Thanks again!

![image](https://github.com/user-attachments/assets/a88218e1-497e-4f70-b57a-b5f4cbe4168a)

**Comment by Netfreak25** [comment]
> @BobHasNoSoul would like to mention that the weird formatting issue with the Amazon tab is still preset.
> 
> I'm not too stressed about this but thought I would mention it.
> 
> Thanks again!
> 
> ![image](https://private-user-images.githubusercontent.com/112329763/383371748-a88218e1-497e-4f70-b57a-b5f4cbe4168a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MjI2OTAsIm5iZiI6MTczMTUyMjM5MCwicGF0aCI6Ii8xMTIzMjk3NjMvMzgzMzcxNzQ4LWE4ODIxOGUxLTQ5N2UtNGY3MC1iNTdhLWI1ZjRjYmU0MTY4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QxODI2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZmJhYjgxN2YwODdiNzdlNGYxZWJmNDk2ODYxMmUzM2YxZDIzZmI3OWIzMjEwOTBlYWI1NTI4NWNiYjExY2VkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bOem_WUtNI9Ne__sqPrFPr6A0IEN_cMUzsizn_IymNk)

acutally that one was on purpuse i guess ;)
the images seem to belong together, could been ment as spacer
